import json
from typing import Any


def _safe_value(value: Any) -> Any:
    """
    Convert values into JSON-safe Python objects.

    EDA results can contain NumPy/Pandas-specific values that
    are not always directly serializable.
    """
    if value is None:
        return None

    if isinstance(value, dict):
        return {
            str(key): _safe_value(val)
            for key, val in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [_safe_value(item) for item in value]

    # Handle NumPy/Pandas scalar types without importing them directly.
    if hasattr(value, "item"):
        try:
            return value.item()
        except (ValueError, TypeError):
            pass

    return value


def _format_data(data: Any) -> str:
    """
    Convert structured EDA information into readable text.

    This text will later be embedded.
    """
    safe_data = _safe_value(data)

    if isinstance(safe_data, (dict, list)):
        return json.dumps(
            safe_data,
            indent=2,
            ensure_ascii=False
        )

    return str(safe_data)


def _create_document(
    *,
    dataset_id: str,
    section: str,
    content: str,
    column: str | None = None,
    analysis_type: str | None = None,
) -> dict:
    """
    Create one knowledge document with metadata.
    """

    metadata = {
        "dataset_id": dataset_id,
        "section": section,
    }

    if column is not None:
        metadata["column"] = column

    if analysis_type is not None:
        metadata["analysis_type"] = analysis_type

    return {
        "text": content,
        "metadata": metadata,
    }


def build_knowledge_documents(
    report: dict,
    dataset_id: str,
) -> list[dict]:
    """
    Convert an EDA report into semantically meaningful
    knowledge documents for the RAG pipeline.

    Parameters
    ----------
    report:
        Existing EDA report generated by DataMind AI.

    dataset_id:
        Unique identifier for the uploaded dataset.

    Returns
    -------
    list[dict]
        Documents containing:
        - text
        - metadata
    """

    documents = []

    # ---------------------------------------------------------
    # 1. Basic dataset information
    # ---------------------------------------------------------

    if "basic_info" in report:
        content = (
            "Dataset overview:\n"
            f"{_format_data(report['basic_info'])}"
        )

        documents.append(
            _create_document(
                dataset_id=dataset_id,
                section="basic_info",
                analysis_type="dataset_overview",
                content=content,
            )
        )

    # ---------------------------------------------------------
    # 2. Column summary
    # ---------------------------------------------------------

    column_summary = report.get("column_summary", {})

    if isinstance(column_summary, dict):
        for column, data in column_summary.items():

            content = (
                f"Column: {column}\n"
                "Column summary:\n"
                f"{_format_data(data)}"
            )

            documents.append(
                _create_document(
                    dataset_id=dataset_id,
                    section="column_summary",
                    column=str(column),
                    analysis_type="column_profile",
                    content=content,
                )
            )

    # ---------------------------------------------------------
    # 3. Missing values
    # ---------------------------------------------------------

    missing_analysis = report.get("missing_analysis", {})

    if isinstance(missing_analysis, dict):
        for column, data in missing_analysis.items():

            content = (
                f"Column: {column}\n"
                "Missing-value analysis:\n"
                f"{_format_data(data)}"
            )

            documents.append(
                _create_document(
                    dataset_id=dataset_id,
                    section="missing_analysis",
                    column=str(column),
                    analysis_type="missing_values",
                    content=content,
                )
            )

    # ---------------------------------------------------------
    # 4. Invalid values
    # ---------------------------------------------------------

    invalid_analysis = report.get(
        "invalid_value_analysis",
        {}
    )

    if isinstance(invalid_analysis, dict):
        for column, data in invalid_analysis.items():

            content = (
                f"Column: {column}\n"
                "Invalid-value analysis:\n"
                f"{_format_data(data)}"
            )

            documents.append(
                _create_document(
                    dataset_id=dataset_id,
                    section="invalid_value_analysis",
                    column=str(column),
                    analysis_type="invalid_values",
                    content=content,
                )
            )

    # ---------------------------------------------------------
    # 5. Numerical statistics
    # ---------------------------------------------------------

    numerical_stats = report.get(
        "numerical_statistics",
        {}
    )

    if isinstance(numerical_stats, dict):
        for column, data in numerical_stats.items():

            content = (
                f"Column: {column}\n"
                "Numerical statistics:\n"
                f"{_format_data(data)}"
            )

            documents.append(
                _create_document(
                    dataset_id=dataset_id,
                    section="numerical_statistics",
                    column=str(column),
                    analysis_type="numerical_statistics",
                    content=content,
                )
            )

    # ---------------------------------------------------------
    # 6. Categorical statistics
    # ---------------------------------------------------------

    categorical_stats = report.get(
        "categorical_statistics",
        {}
    )

    if isinstance(categorical_stats, dict):
        for column, data in categorical_stats.items():

            content = (
                f"Column: {column}\n"
                "Categorical statistics:\n"
                f"{_format_data(data)}"
            )

            documents.append(
                _create_document(
                    dataset_id=dataset_id,
                    section="categorical_statistics",
                    column=str(column),
                    analysis_type="categorical_statistics",
                    content=content,
                )
            )

    # ---------------------------------------------------------
    # 7. Datetime statistics
    # ---------------------------------------------------------

    datetime_stats = report.get(
        "datetime_statistics",
        {}
    )

    if isinstance(datetime_stats, dict):
        for column, data in datetime_stats.items():

            content = (
                f"Column: {column}\n"
                "Datetime statistics:\n"
                f"{_format_data(data)}"
            )

            documents.append(
                _create_document(
                    dataset_id=dataset_id,
                    section="datetime_statistics",
                    column=str(column),
                    analysis_type="datetime_statistics",
                    content=content,
                )
            )

    # ---------------------------------------------------------
    # 8. Outlier analysis
    # ---------------------------------------------------------

    outlier_analysis = report.get(
        "outlier_analysis",
        {}
    )

    if isinstance(outlier_analysis, dict):
        for column, data in outlier_analysis.items():

            content = (
                f"Column: {column}\n"
                "Outlier analysis:\n"
                f"{_format_data(data)}"
            )

            documents.append(
                _create_document(
                    dataset_id=dataset_id,
                    section="outlier_analysis",
                    column=str(column),
                    analysis_type="outliers",
                    content=content,
                )
            )

    # ---------------------------------------------------------
    # 9. Distribution analysis
    # ---------------------------------------------------------

    distribution_analysis = report.get(
        "distribution_analysis",
        {}
    )

    if isinstance(distribution_analysis, dict):
        for column, data in distribution_analysis.items():

            content = (
                f"Column: {column}\n"
                "Distribution analysis:\n"
                f"{_format_data(data)}"
            )

            documents.append(
                _create_document(
                    dataset_id=dataset_id,
                    section="distribution_analysis",
                    column=str(column),
                    analysis_type="distribution",
                    content=content,
                )
            )

    # ---------------------------------------------------------
    # 10. Kurtosis analysis
    # ---------------------------------------------------------

    kurtosis_analysis = report.get(
        "kurtosis_analysis",
        {}
    )

    if isinstance(kurtosis_analysis, dict):
        for column, data in kurtosis_analysis.items():

            content = (
                f"Column: {column}\n"
                "Kurtosis analysis:\n"
                f"{_format_data(data)}"
            )

            documents.append(
                _create_document(
                    dataset_id=dataset_id,
                    section="kurtosis_analysis",
                    column=str(column),
                    analysis_type="kurtosis",
                    content=content,
                )
            )

    # ---------------------------------------------------------
    # 11. Correlation analysis
    # ---------------------------------------------------------

    if "correlation_analysis" in report:

        content = (
            "Dataset correlation analysis:\n"
            f"{_format_data(report['correlation_analysis'])}"
        )

        documents.append(
            _create_document(
                dataset_id=dataset_id,
                section="correlation_analysis",
                analysis_type="correlation",
                content=content,
            )
        )

    # ---------------------------------------------------------
    # 12. Duplicate analysis
    # ---------------------------------------------------------

    if "duplicate_analysis" in report:

        content = (
            "Dataset duplicate analysis:\n"
            f"{_format_data(report['duplicate_analysis'])}"
        )

        documents.append(
            _create_document(
                dataset_id=dataset_id,
                section="duplicate_analysis",
                analysis_type="duplicates",
                content=content,
            )
        )

    return documents